[package]
name = "github-socket"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "*"
tokio = { version = "*", features = ["rt-multi-thread", "macros"] }
reqwest = "*"
serde = "*"
serde_json = "*"
