name: Test A

on:
  push:

jobs:
  test:
    name: Test A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run
        run: cargo run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
