name: Test A

on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        action: [1, 2, 3, 4]
    name: Test A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Run
        run: cargo run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION: ${{ matrix.action }}
